
(function(){
const $=(s,r=document)=>r.querySelector(s);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function load(p){const r=await fetch(p,{cache:'no-store'});if(!r.ok)throw new Error(p);return r.json();}
function fcard(f){return `<article class="festival-card"><span class="chip">${esc(f.type)}</span><h3>${esc(f.titleEn)}</h3><p lang="ta"><strong>${esc(f.titleTa)}</strong></p><p class="meta">${esc(f.tamilMonth)} · ${esc(f.season||'')}</p><p>${esc(f.summary)}</p><div>${(f.tags||[]).slice(0,3).map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div><p><a class="festival-btn secondary" href="festival-details.html?id=${encodeURIComponent(f.id)}">Open details</a></p></article>`}
async function renderFestivalCalendar(){const box=$('#festival-list');if(!box)return;const data=await load('/data/festivals/festival_master.json');const search=$('#festival-search'),month=$('#festival-month-filter'),type=$('#festival-type-filter');[...new Set(data.map(x=>x.tamilMonth))].forEach(m=>month.insertAdjacentHTML('beforeend',`<option>${esc(m)}</option>`));[...new Set(data.map(x=>x.type))].forEach(t=>type.insertAdjacentHTML('beforeend',`<option>${esc(t)}</option>`));function apply(){let q=(search.value||'').toLowerCase(),m=month.value,t=type.value;let out=data.filter(f=>(m==='all'||f.tamilMonth===m)&&(t==='all'||f.type===t)&&(`${f.titleEn} ${f.titleTa} ${f.summary} ${(f.tags||[]).join(' ')}`.toLowerCase().includes(q)));box.innerHTML=out.map(fcard).join('')||'<p>No festival found.</p>';$('#festival-count').textContent=`${out.length} festival records shown`;}[search,month,type].forEach(el=>el.addEventListener(el===search?'input':'change',apply));apply();}
async function renderYear(){const box=$('#festival-year-list');if(!box)return;const months=await load('/data/festivals/months/index.json');box.innerHTML=months.map(m=>`<article class="month-card"><h3>${esc(m.nameEn)}</h3><p lang="ta">${esc(m.nameTa)}</p><p class="meta">${esc(m.highlights.join(', '))}</p><a class="festival-btn secondary" href="festival-month.html?month=${encodeURIComponent(m.id)}">View month</a></article>`).join('')}
async function renderMonth(){const box=$('#festival-month-list'),sel=$('#month-page-select');if(!box||!sel)return;const months=await load('/data/festivals/months/index.json');months.forEach(m=>sel.insertAdjacentHTML('beforeend',`<option value="${esc(m.id)}">${esc(m.nameEn)} / ${esc(m.nameTa)}</option>`));const params=new URLSearchParams(location.search);if(params.get('month'))sel.value=params.get('month');async function apply(){const data=await load(`/data/festivals/months/${sel.value}.json`);box.innerHTML=data.map(fcard).join('')||'<p>No records.</p>'}sel.addEventListener('change',apply);apply()}
async function renderMuruganFestivals(){const box=$('#murugan-festival-list');if(!box)return;const data=await load('/data/murugan-festivals/murugan_festivals.json');box.innerHTML=data.map(fcard).join('')}
window.addEventListener('DOMContentLoaded',()=>{renderFestivalCalendar().catch(console.error);renderYear().catch(console.error);renderMonth().catch(console.error);renderMuruganFestivals().catch(console.error);});
})();
