(function(){
  'use strict';
  const KG = { graph:null, prompts:null };
  const $ = (s,r=document)=>r.querySelector(s);
  const $$ = (s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  async function json(path){ try{ const r=await fetch(path,{cache:'no-store'}); if(!r.ok) throw new Error(r.status); return await r.json(); } catch(e){ console.warn('[KG] load failed',path,e); return null; } }
  function node(id){ return KG.graph.nodes.find(n=>n.id===id); }
  function edgesFor(id){ return KG.graph.edges.filter(e=>e.source===id||e.target===id); }
  function related(id){ const found=edgesFor(id); return found.map(e=>({edge:e,item:node(e.source===id?e.target:e.source)})).filter(x=>x.item); }
  function score(item,q){ const text=[item.id,item.title,item.titleTa,item.summary,(item.tags||[]).join(' ')].join(' ').toLowerCase(); const query=q.toLowerCase().trim(); if(!query) return 0; let s=0; if(item.id===query) s+=50; if((item.title||'').toLowerCase()===query) s+=45; if((item.titleTa||'').includes(q)) s+=40; if((item.title||'').toLowerCase().includes(query)) s+=30; if((item.tags||[]).some(t=>t.toLowerCase().includes(query))) s+=22; if(text.includes(query)) s+=10; query.split(/\s+/).forEach(p=>{ if(p.length>2 && text.includes(p)) s+=4; }); return s; }
  function card(item, opts={}){ return `<article><div class="meta">${esc(item.type||'knowledge')}</div><h3>${esc(item.titleTa||item.title)}</h3><p class="kg-muted">${esc(item.title||'')}</p><p>${esc(item.summary||'')}</p><div class="kg-tags">${(item.tags||[]).slice(0,6).map(t=>`<span class="kg-tag">${esc(t)}</span>`).join('')}</div><div class="kg-toolbar"><a class="kg-btn secondary" href="${esc(item.url||'recommendations.html?id='+encodeURIComponent(item.id))}">Open</a><a class="kg-btn" href="recommendations.html?id=${encodeURIComponent(item.id)}">Related</a></div></article>`; }
  function renderSearch(q){ const box=$('#kg-results'); if(!box) return; const ranked=KG.graph.nodes.map(n=>({...n,_score:score(n,q)})).filter(n=>n._score>0).sort((a,b)=>b._score-a._score); box.innerHTML = ranked.length ? ranked.map(card).join('') : `<div class="kg-warning">No exact verified result found. Try Murugan, Palani, Vel, Thai Poosam, Skanda Sashti or Arupadai Veedu.</div>`; const count=$('#kg-count'); if(count) count.textContent = ranked.length + ' verified result(s)'; }
  function initAISearch(){ const input=$('#kg-query'); const params=new URLSearchParams(location.search); if(input && params.get('q')) input.value=params.get('q'); const run=()=>renderSearch(input?.value||'murugan'); $('#kg-search-btn')?.addEventListener('click',run); input?.addEventListener('input',run); run(); }
  function initGraph(){ const nodes=$('#kg-nodes'), edges=$('#kg-edges'); if(nodes) nodes.innerHTML=KG.graph.nodes.map(card).join(''); if(edges) edges.innerHTML=KG.graph.edges.map(e=>{const a=node(e.source), b=node(e.target); return `<div class="kg-edge"><span class="kg-node">${esc(a?.title||e.source)}</span><span class="kg-relation">${esc(e.relation)}</span><span class="kg-node">${esc(b?.title||e.target)}</span></div>`}).join(''); const k=$('#kg-kpi'); if(k) k.innerHTML=`<div><strong>${KG.graph.nodes.length}</strong><span>Knowledge nodes</span></div><div><strong>${KG.graph.edges.length}</strong><span>Verified links</span></div><div><strong>6</strong><span>Arupadai Veedu focus</span></div>`; }
  function initRecommendations(){ const id=new URLSearchParams(location.search).get('id')||'murugan'; const base=node(id)||node('murugan'); const hero=$('#rec-hero'); if(hero) hero.innerHTML=`<p class="eyebrow">Recommendation engine</p><h1>${esc(base.titleTa||base.title)}</h1><p>${esc(base.summary)}</p>`; const rel=related(base.id); const list=$('#rec-list'); if(list) list.innerHTML=rel.length?rel.map(x=>card(x.item)).join(''):'<div class="kg-warning">No related items yet.</div>'; }
  function answerFor(q){ const ranked=KG.graph.nodes.map(n=>({...n,_score:score(n,q)})).filter(n=>n._score>0).sort((a,b)=>b._score-a._score); if(!ranked.length) return KG.prompts.fallback; const top=ranked[0]; const rel=related(top.id).slice(0,4).map(x=>x.item.title).join(', '); return `${top.title}: ${top.summary}${rel? ' Related verified links: '+rel+'.':''}`; }
  function initGuide(){ const qs=$('#guide-questions'), ans=$('#guide-answer'), input=$('#guide-input'); if(qs) qs.innerHTML=(KG.graph.guidedQuestions||KG.prompts.suggestions||[]).map(q=>`<button class="kg-question" data-q="${esc(q)}">${esc(q)}</button>`).join(''); const ask=q=>{ if(ans) ans.innerHTML=`<div class="kg-answer"><strong>Murugan Guide</strong><p>${esc(answerFor(q))}</p><p class="kg-muted">This answer is generated from the local verified website knowledge graph.</p></div>`; } ; qs?.addEventListener('click',e=>{const b=e.target.closest('[data-q]'); if(b) ask(b.dataset.q);}); $('#guide-btn')?.addEventListener('click',()=>ask(input?.value||'')); ask('Murugan'); }
  function initPaths(){ const el=$('#kg-path'); if(!el) return; const path=['murugan','vel','arupadai-veedu','palani','om-saravana-bhava','thai-poosam']; el.innerHTML=path.map(id=>{const n=node(id); return `<li><strong>${esc(n?.title||id)}</strong><br><span class="kg-muted">${esc(n?.summary||'')}</span></li>`}).join(''); }
  async function init(){ KG.graph=await json('data/knowledge/knowledge_graph.json'); KG.prompts=await json('data/knowledge/ai_guide_prompts.json')||{}; if(!KG.graph) return; initAISearch(); initGraph(); initRecommendations(); initGuide(); initPaths(); }
  document.addEventListener('DOMContentLoaded',init);
})();
