(function(){
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function load(path){const r=await fetch(path,{cache:'no-store'}); if(!r.ok) throw new Error(path); return r.json();}
function card(t){return `<article class="temple-pro-card"><span class="temple-chip">${esc(t.category)}</span><h3>${esc(t.titleEn)}</h3><p lang="ta"><strong>${esc(t.titleTa)}</strong></p><p class="meta">📍 ${esc(t.district)}, ${esc(t.state)}</p><p>${esc(t.summary)}</p><div>${(t.features||[]).slice(0,3).map(x=>`<span class="temple-chip">${esc(x)}</span>`).join('')}</div><p><a class="temple-btn" href="temple-details.html?id=${encodeURIComponent(t.id)}">View details</a></p></article>`}
async function renderMaster(){const box=$('#temple-pro-list'); if(!box)return; const data=await load('/data/temples/temple_master.json'); const search=$('#temple-pro-search'); const cat=$('#temple-pro-category'); const dist=$('#temple-pro-district'); [...new Set(data.map(x=>x.category))].sort().forEach(v=>cat&&cat.insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`)); [...new Set(data.map(x=>x.district))].sort().forEach(v=>dist&&dist.insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`)); function apply(){let q=(search?.value||'').toLowerCase();let c=cat?.value||'All';let d=dist?.value||'All';let f=data.filter(t=>(c==='All'||t.category===c)&&(d==='All'||t.district===d)&&(`${t.titleEn} ${t.titleTa} ${t.district} ${(t.tags||[]).join(' ')}`.toLowerCase().includes(q))); box.innerHTML=f.map(card).join('')||'<p>No temple found.</p>'; $('#temple-count')&&($('#temple-count').textContent=`${f.length} temples shown`)} ['input','change'].forEach(e=>{search?.addEventListener(e,apply);cat?.addEventListener(e,apply);dist?.addEventListener(e,apply)});apply();}
async function renderArupadai(){const box=$('#arupadai-list'); if(!box)return; const data=await load('/data/temples/arupadai_veedu.json'); box.innerHTML=data.map((t,i)=>`<div class="route-stop"><div><h3>${esc(t.titleEn)}</h3><p lang="ta">${esc(t.titleTa)}</p><p>${esc(t.summary)}</p><a class="temple-btn secondary" href="temple-details.html?id=${t.id}">Open abode</a></div></div>`).join('');}
async function renderTimeline(){const box=$('#temple-timeline-list'); if(!box)return; const data=await load('/data/temples/temple_timeline.json'); box.innerHTML=data.map(x=>`<div class="timeline-item"><h3>${esc(x.period)}</h3><p>${esc(x.description)}</p></div>`).join('')}
async function renderArchitecture(){const box=$('#architecture-list'); if(!box)return; const data=await load('/data/architecture/architecture.json'); box.innerHTML=data.map(x=>`<article class="temple-pro-card"><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><ul>${(x.notes||[]).map(n=>`<li>${esc(n)}</li>`).join('')}</ul></article>`).join('')}
async function renderTravel(){const box=$('#travel-list'); if(!box)return; const data=await load('/data/travel/travel_guides.json'); box.innerHTML=data.map(x=>`<article class="temple-pro-card"><h3>${esc(x.title)}</h3><p class="meta">${esc(x.region)}</p><ul>${x.tips.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></article>`).join('')}
async function renderPilgrimage(){const box=$('#pilgrimage-list'); if(!box)return; const data=await load('/data/pilgrimage/pilgrimage_routes.json'); box.innerHTML=data.map(x=>`<article class="temple-pro-card"><h3>${esc(x.title)}</h3><p class="meta">${esc(x.duration)}</p><div class="route-list">${x.stops.map(s=>`<div class="route-stop"><div><strong>${esc(s)}</strong><br><a href="temple-details.html?id=${esc(s)}">Open temple</a></div></div>`).join('')}</div><p>${esc(x.note)}</p></article>`).join('')}
async function renderMap(){const box=$('#temple-map-list'); if(!box)return; const data=await load('/data/maps/temple_coordinates.json'); box.innerHTML=data.map(x=>`<article class="temple-pro-card"><h3>${esc(x.titleEn)}</h3><p>${esc(x.district)}</p><p class="meta">Lat: ${esc(x.location.lat)} | Lng: ${esc(x.location.lng)}</p><a class="temple-btn secondary" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${x.location.lat},${x.location.lng}">Open map</a></article>`).join('')}
window.addEventListener('DOMContentLoaded',()=>{renderMaster().catch(console.error);renderArupadai().catch(console.error);renderTimeline().catch(console.error);renderArchitecture().catch(console.error);renderTravel().catch(console.error);renderPilgrimage().catch(console.error);renderMap().catch(console.error);});
})();
